import type { Metadata } from 'next';
import { ROBOTO } from '@/config/font';
import '@/app/globals.css';

import OcAppBar from '@/components/organisms/app-bar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function BaseLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body
				className={`${ROBOTO.className} p-3 min-h-screen antialiased`}
			>
				<OcAppBar />
				{children}
			</body>
		</html>
	);
}
